title: Noted
markdown: kramdown
url: "babaid.github.io"
baseurl: ""

# for atom feed
author:
  name: Dezsö Babai 
  email: manobacsi666@gmail.com

plugins:
  - jekyll-paginate
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-menus

paginate_path: "/page:num/"

paginate: 5

collections_dir: all_collections
collections:
  posts:
    output: true
  projects:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: "post"
  - scope:
      path: "_posts"
    values:
      layout: "post"
      permalink: /posts/:categories/:year/:month/:day/:title/

exclude: ["LICENSE", "README.md"]
